In [4]:
import numpy as np

In [13]:
a=np.random.uniform(1,20,15)
print(a)

[14.41217953  3.89363369 19.77581312 17.65627645 19.07805013 17.67194984
 10.71079693  3.98680107  4.13422852  8.64945559 12.19291007 12.7513806
  1.21535447 11.82156429  4.11290264]


In [14]:
import numpy as np
array = a;
print("Array : " + str(array))
n = array.size
N = 3
M = n//N
reshaped = array.reshape((N, M))
print("First Reshaped Array 3 x 5 : ")
print(reshaped)

Array : [14.41217953  3.89363369 19.77581312 17.65627645 19.07805013 17.67194984
 10.71079693  3.98680107  4.13422852  8.64945559 12.19291007 12.7513806
  1.21535447 11.82156429  4.11290264]
First Reshaped Array 3 x 5 : 
[[14.41217953  3.89363369 19.77581312 17.65627645 19.07805013]
 [17.67194984 10.71079693  3.98680107  4.13422852  8.64945559]
 [12.19291007 12.7513806   1.21535447 11.82156429  4.11290264]]


In [15]:
a = reshaped
b = a
b[np.arange(len(a)), a.argmax(1)] = 0
print(b)

[[14.41217953  3.89363369  0.         17.65627645 19.07805013]
 [ 0.         10.71079693  3.98680107  4.13422852  8.64945559]
 [12.19291007  0.          1.21535447 11.82156429  4.11290264]]
